DROP TABLE "USER_INFO";

CREATE TABLE "USER_INFO"
(
  USERNAME character(20) NOT NULL,
  PASSWORD character(20) NOT NULL,
  ENABLED boolean NOT NULL,
  AUTHORITY character(20) NOT NULL,
  CONSTRAINT username PRIMARY KEY (username)
);


INSERT INTO "USER_INFO" (USERNAME,PASSWORD, ENABLED, AUTHORITY)
VALUES ('test', 'test', TRUE, 'ROLE_USER');